//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_hecsa
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_email_env
    {
        public System.Guid email_env_ID { get; set; }
        public Nullable<int> email_env_est { get; set; }
        public string email { get; set; }
        public string usuario { get; set; }
        public string clave { get; set; }
        public string asunto { get; set; }
        public string servidor_smtp { get; set; }
        public Nullable<int> puerto { get; set; }
        public Nullable<System.DateTime> registro { get; set; }
    }
}
