//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_hecsa
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_comp
    {
        public System.Guid compra_ID { get; set; }
        public string cod_comp { get; set; }
        public Nullable<int> est_comp_ID { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string categoria { get; set; }
        public string comp_desc { get; set; }
        public string caracteristica { get; set; }
        public Nullable<decimal> costo { get; set; }
        public Nullable<System.DateTime> registro { get; set; }
        public System.Guid centro_ID { get; set; }
    
        public virtual fact_est_comp fact_est_comp { get; set; }
        public virtual inf_centro inf_centro { get; set; }
    }
}
