//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_hecsa
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_vnta_inv
    {
        public System.Guid vnta_inv_ID { get; set; }
        public System.Guid inventario_ID { get; set; }
        public Nullable<decimal> costo { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<int> porcentaje_desc { get; set; }
        public System.Guid vnta_ID { get; set; }
    
        public virtual inf_vnta inf_vnta { get; set; }
    }
}
