//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_hecsa
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_clte_contacto
    {
        public System.Guid clte_contacto_ID { get; set; }
        public Nullable<int> clte_cont_tipo_ID { get; set; }
        public string nombres { get; set; }
        public string apaterno { get; set; }
        public string amaterno { get; set; }
        public string tel { get; set; }
        public string tel_atl { get; set; }
        public string email { get; set; }
        public string email_alt { get; set; }
        public string callenum { get; set; }
        public string d_codigo { get; set; }
        public string id_asenta_cpcons { get; set; }
        public Nullable<System.DateTime> registro { get; set; }
        public System.Guid clte_ID { get; set; }
    
        public virtual fact_clte_cont_tipo fact_clte_cont_tipo { get; set; }
        public virtual inf_clte inf_clte { get; set; }
    }
}
