//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_hecsa
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_usr_escolar
    {
        public System.Guid usr_escolar_ID { get; set; }
        public Nullable<int> tipo_escolar_ID { get; set; }
        public string grado_escolar { get; set; }
        public string titulo { get; set; }
        public string fecha_escolar { get; set; }
        public System.Guid usuario_ID { get; set; }
    
        public virtual fact_tipo_escolar fact_tipo_escolar { get; set; }
        public virtual inf_usuario inf_usuario { get; set; }
    }
}
