//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_hecsa
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_vnta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inf_vnta()
        {
            this.inf_vnta_inv = new HashSet<inf_vnta_inv>();
        }
    
        public System.Guid vnta_ID { get; set; }
        public Nullable<int> est_vnta_ID { get; set; }
        public string cod_vnta { get; set; }
        public Nullable<int> vnta_tipo_ID { get; set; }
        public Nullable<System.DateTime> registro { get; set; }
        public System.Guid centro_ID { get; set; }
        public System.Guid usuario_ID { get; set; }
        public System.Guid clte_ID { get; set; }
    
        public virtual fact_est_vnta fact_est_vnta { get; set; }
        public virtual inf_centro inf_centro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inf_vnta_inv> inf_vnta_inv { get; set; }
    }
}
