//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_hecsa
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_prov_contacto
    {
        public System.Guid prov_contacto_ID { get; set; }
        public string dpto { get; set; }
        public string nombres { get; set; }
        public string apaterno { get; set; }
        public string amaterno { get; set; }
        public string tel { get; set; }
        public string tel_atl { get; set; }
        public string email { get; set; }
        public string email_alt { get; set; }
        public Nullable<System.DateTime> registro { get; set; }
        public System.Guid prov_ID { get; set; }
    
        public virtual inf_proveedor inf_proveedor { get; set; }
    }
}
