//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_hecsa
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_centro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inf_centro()
        {
            this.inf_centro_ctrl = new HashSet<inf_centro_ctrl>();
            this.inf_clte = new HashSet<inf_clte>();
            this.inf_comp = new HashSet<inf_comp>();
            this.inf_proveedor = new HashSet<inf_proveedor>();
            this.inf_vnta = new HashSet<inf_vnta>();
        }
    
        public System.Guid centro_ID { get; set; }
        public Nullable<int> centro_tipo_ID { get; set; }
        public int est_cnt_ID { get; set; }
        public System.Guid licencia_ID { get; set; }
        public string cod_centro { get; set; }
        public string centro_nom { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string callenum { get; set; }
        public string d_codigo { get; set; }
        public string id_asenta_cpcons { get; set; }
        public Nullable<System.DateTime> registro { get; set; }
        public System.Guid empresa_ID { get; set; }
    
        public virtual fact_centro_tipo fact_centro_tipo { get; set; }
        public virtual fact_est_cnt fact_est_cnt { get; set; }
        public virtual fact_licencia fact_licencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inf_centro_ctrl> inf_centro_ctrl { get; set; }
        public virtual inf_emp inf_emp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inf_clte> inf_clte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inf_comp> inf_comp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inf_proveedor> inf_proveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inf_vnta> inf_vnta { get; set; }
    }
}
