//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_hecsa
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_rpt_remision
    {
        public System.Guid vnta_ID { get; set; }
        public string cod_vnta { get; set; }
        public Nullable<System.DateTime> registro { get; set; }
        public string cod_centro { get; set; }
        public string licencia_desc { get; set; }
        public string centro_nom { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string callenum { get; set; }
        public string d_asenta { get; set; }
        public string d_codigo { get; set; }
        public string d_mnpio { get; set; }
        public string d_estado { get; set; }
        public string d_ciudad { get; set; }
        public string nombres_oper { get; set; }
        public string apaterno_oper { get; set; }
        public string amaterno_oper { get; set; }
        public string cod_clte { get; set; }
        public string nombres { get; set; }
        public string apaterno { get; set; }
        public string amaterno { get; set; }
        public string cod_inv { get; set; }
        public string nivel_escolar_desc { get; set; }
        public string grado_escolar_desc { get; set; }
        public string categoria { get; set; }
        public string inv_desc { get; set; }
        public string caracteristica { get; set; }
        public Nullable<decimal> costo { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<int> porcentaje_desc { get; set; }
        public Nullable<double> total_inv { get; set; }
    }
}
